language: cpp
sudo: required

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev

git:
  submodules: false

before_install:
  - sudo apt-get install libboost-dev
  - pip install --user cpp-coveralls
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - cd Build
  - bash linux.sh
  - cd Linux/Release/Tests/
  - ./Tests

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*Tests/.*.cpp.*"
